name: Main Frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - frontend/**
  workflow_dispatch:

jobs:

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install jq
      run: sudo apt-get install jq
    - name: Read JSON file
      id: json
      run: |
        VALUE=$(jq -r '.version' ./frontend/package.json)
        echo "::set-output name=value::$VALUE"
    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:frontend"
        tags: ${{ secrets.REPOSITORY }}:frontend-latest,${{ secrets.REPOSITORY }}:frontend-${{ steps.json.outputs.value }}
        labels: ${{ secrets.REPOSITORY }}:frontend-latest,${{ secrets.REPOSITORY }}:frontend-${{ steps.json.outputs.value }}